spring.application.name=Usuarios-Z
server.port=8081

# ¡OJO AQUÍ! Cambiamos localhost por el nombre del servicio de Kubernetes
spring.datasource.url=jdbc:postgresql://postgres-service:5432/godofgames_usuarios
spring.datasource.username=postgres
spring.datasource.password=postgres 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html