# PARTE 1: EL CABLE DE RED (Service)
# Esto crea una IP interna fija para que nuestro código Java siempre encuentre la base de datos.
apiVersion: v1
kind: Service
metadata:
  name: postgres-service # Nombre clave en la red
spec:
  selector:
    app: base-de-datos-usuarios
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # ClusterIP significa que es privado, nadie desde fuera (internet) puede hackear la base de datos.

---
# PARTE 2: EL CONTENEDOR FÍSICO (Deployment)
# Aquí le decimos al "gerente" qué base de datos instalar.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1 # Solo queremos 1 base de datos principal
  selector:
    matchLabels:
      app: base-de-datos-usuarios
  template:
    metadata:
      labels:
        app: base-de-datos-usuarios
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "godofgames_usuarios"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "admin123"